# Name of the site shown in the header and browser tab
site_name: ""

theme:
  name: material
  logo: assets/logo.svg

  palette:
    # Primary and accent colors used in the theme
    primary: 'teal'
    accent: 'blue'

  font:
    # Font used for regular text and code blocks
    text: Poppins
    code: Fira Code

  features:
    # UI features from Material for MkDocs
    - navigation.instant      # Instant page transitions without full reload
    - navigation.tabs         # Navigation tabs at the top
    - navigation.top          # Scroll to top on new navigation
    - navigation.expand       # Keep navigation tree expanded
    - content.code.copy       # Add "copy" buttons to code blocks

# Navigation structure shown in the sidebar/menu
nav:
  - Home: index.md
  - Networks:
      - Concepts: redes/conceitos.md
  - Linux:
      - Commands: linux/comandos.md        # Fixed path from 'git-github' to 'linux'
  - Git & GitHub:
      - Commands: git-github/comandos.md
      - Concepts: git-github/conceitos.md
  - Docker:
      - Useful Commands: docker/comandos.md
  - Kubernetes:
      - Concepts: kubernetes/conceitos.md
  - GitHub Actions:
      - Practical Examples: github-actions/exemplos.md

# Extra custom CSS file
extra_css:
  - styles/extra.css
