name: Auto Deploy S3
on:
    push:
        branches:
            - main
            - feature/*
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Pip Upgrade
              run: |
                pip install --upgrade pip

            - name: Install mkdocs
              run: |
                pip install mkdocs
                pip install mkdocs-material
                pip install mkdocs-minify-plugin

            - name: Verification
              run: |
                mkdocs --version

            - name: Build Site
              run: |
                mkdocs gh-deploy --force
            
    
    deploy:
        needs: build
        uses: vinicius3516/devops-tools/.github/workflows/deploy-s3.yml@main
        secrets:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            bucket_name: ${{ secrets.S3_BUCKET_NAME }}
            region: ${{ secrets.AWS_REGION }}